# Generated by Django 5.2.1 on 2025-05-28 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_alter_lead_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='status',
        ),
        migrations.AddField(
            model_name='lead',
            name='stage',
            field=models.CharField(choices=[('new', 'New'), ('engaged', 'Engaged'), ('proposal', 'Proposal'), ('won', 'Won'), ('lost', 'Lost')], default='new', max_length=20),
        ),
    ]
